#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

GINGERVIEW_REPO="https://github.com/gingeradditive/GingerView.git"
DEPS=(git nginx)

apt-get install --yes "${DEPS[@]}"

########################################
# Config Webserver                     #
########################################

echo "Remove the default site"
rm /etc/nginx/sites-enabled/default

echo "Copy the nginx configurations"
cp /files/mainsail-nginx/mainsail /etc/nginx/sites-available/mainsail
cp /files/mainsail-nginx/common_vars.conf /etc/nginx/conf.d/common_vars.conf
cp /files/mainsail-nginx/upstreams.conf /etc/nginx/conf.d/upstreams.conf

echo "Enable the site"
ln -s /etc/nginx/sites-available/mainsail /etc/nginx/sites-enabled/

########################################
# Modify Logrotate for nginx           #
########################################

echo "Modify logrotate cycle from 14d to 2d"
sudo sed -i 's/rotate 14/rotate 2/' /etc/logrotate.d/nginx

create_user_directories

echo "Linking log files"
ln -s /var/log/nginx/mainsail-access.log /home/"${BASE_USER}"/printer_data/logs/mainsail-access.log
ln -s /var/log/nginx/mainsail-error.log /home/"${BASE_USER}"/printer_data/logs/mainsail-error.log

########################################
# Switch to BASE_USER home directory   #
########################################

pushd /home/"${BASE_USER}" &> /dev/null || exit 1

########################################
# Clone GingerView repository          #
########################################

echo "Cloning GingerView"
sudo -u "${BASE_USER}" git clone --depth 1 "${GINGERVIEW_REPO}" /home/"${BASE_USER}"/mainsail

if [[ ! -d /home/"${BASE_USER}"/mainsail/build ]]; then
    echo "Missing GingerView build artifacts in /home/${BASE_USER}/mainsail/build"
    exit 1
fi

########################################
# Fix userrights                       #
########################################

gpasswd -a www-data "${BASE_USER}"
chmod g+x /home/"${BASE_USER}"

########################################
# Remove old mainsail.cfg link         #
########################################

rm -f /home/"${BASE_USER}"/printer_data/config/mainsail.cfg

########################################
# Return to last directory             #
########################################

popd &> /dev/null || exit 1
