#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

REPO="https://github.com/kyleisah/Klipper-Adaptive-Meshing-Purging.git"
DEPS="git"

########################################
# Install dependencies                 #
########################################

apt-get install --yes "${DEPS}"

########################################
# Save current dir and switch to home  #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1

########################################
# Clone repository                     #
########################################

echo "Cloning Repository"
sudo -u "${BASE_USER}" git clone ${REPO} Klipper-Adaptive-Meshing-Purging
ln -s /home/${BASE_USER}/Klipper-Adaptive-Meshing-Purging/Configuration /home/${BASE_USER}/printer_data/config/KAMP
cp /home/${BASE_USER}/Klipper-Adaptive-Meshing-Purging/Configuration/KAMP_Settings.cfg /home/${BASE_USER}/printer_data/config/KAMP_Settings.cfg

########################################
# Return to saved directory            #
########################################

popd &> /dev/null || exit 1

########################################
# Add config to moonraker.conf         #
########################################

if [[ -f $MOONRAKER_CONFIG ]]; then
    cat /files/moonraker_kamp.conf >> "$MOONRAKER_CONFIG"
fi