#!/bin/bash
set -xe
export LC_ALL=C

########################################
# Functions and Basic Configuration    #
########################################

# Load common functions and set up cleanup trap
source /common.sh
install_cleanup_trap

# Load additional configuration (e.g., BASE_USER)
source /files/00-config

########################################
# Configuration                        #
########################################

REPO="https://github.com/Howchoo/pi-power-button"
DEPS="git"

########################################
# Install dependencies                 #
########################################

apt-get install --yes "${DEPS}"

########################################
# Save current dir and switch to home  #
########################################

pushd "/home/${BASE_USER}" &> /dev/null || exit 1

########################################
# Clone repository                     #
########################################

echo "Cloning Repository"
sudo -u "${BASE_USER}" git clone ${REPO} pi-power-button

##############################################
# Jump into pi-power-button, run installer   #
# and go back to home                        #
##############################################

echo "Execute installer"
pushd "pi-power-button" &> /dev/null || exit 1

sudo -u "${BASE_USER}" ./script/install

popd &> /dev/null || exit 1

########################################
# Return to saved directory            #
########################################

popd &> /dev/null || exit 1
